spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: ${DB_USERNAME:root}  # Use environment variable for security
    password: ${DB_PASSWORD:root@12}  # Use environment variable for security
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Changed to validate for production environment
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      jdbc:
      time_zone: UTC

management:
 endpoints:
    web:
     exposure:
       include: health,info  # Expose the health and info endpoints

server:
  port: 9093

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:
    prefer-ip-address: true

# Uncomment if you want to enable Ribbon load balancing (client-side load balancing):
# loadbalancer.ribbon.enabled: true
